In [2]:
import pandas as pd
import numpy as np
import matplotlib as pl
import seaborn as sns

In [3]:
df= pd.read_csv("C:/Users/akash/Datasets/IRIS.csv")
df

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
df.shape

(150, 5)

In [5]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [6]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [7]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [9]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [11]:
X=df.iloc[:,[0,1,2,3]]
X

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [12]:
Y= df.iloc[:,4]
Y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: species, Length: 150, dtype: object

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [14]:
X_train, X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.25)

In [15]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()

In [17]:
X_train=sc_X.fit_transform(X_train)
X_test =sc_X.fit_transform(X_test)

In [19]:
Classifier = GaussianNB()
Classifier.fit(X_train,Y_train)

GaussianNB()

In [21]:
Y_pred = Classifier.predict(X_test)

In [22]:
from sklearn.metrics import accuracy_score
accuracy =  accuracy_score(Y_test,Y_pred)*100
accuracy

92.10526315789474

In [24]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(Y_test,Y_pred)

In [25]:
cm

array([[ 7,  0,  0],
       [ 0, 18,  0],
       [ 0,  3, 10]], dtype=int64)

In [26]:
TP=cm[0,[0]]
print(TP)

[7]


In [30]:
TN=cm[[[1],[2]],[1,2]]
print(TN)

[[18  0]
 [ 3 10]]


In [32]:
FP=cm[[1,2],0]
print(FP)

[0 0]


In [35]:
FN=cm[0,[1,2]]
print(FN)

[0 0]


In [36]:
accuracy = (TP+TN)/(TP+TN+FP+FN)
print(accuracy)

[[1. 1.]
 [1. 1.]]


In [37]:
error_rate=(FP+FN)/(TP+TN+FP+FN)
print(error_rate)

[[0. 0.]
 [0. 0.]]


In [39]:
precision = TP/(TP+FP)
print(precision)

[1. 1.]


In [40]:
Recall =(TP/(TP+FN))
print(Recall)

[1. 1.]


In [42]:
specificity=(TN/TN+FP)
print(specificity)

[[ 1. nan]
 [ 1.  1.]]


C:\Users\akash\AppData\Local\Temp/ipykernel_18560/1821340187.py:1: RuntimeWarning: invalid value encountered in true_divide
  specificity=(TN/TN+FP)


In [43]:
data=[[5.4,3.9,1.7,0.4]]
spec= Classifier.predict(data)
spec

array(['Iris-virginica'], dtype='<U15')

In [44]:
import pickle

In [45]:
pickle.dump(Classifier, open('Classifier.pkl','wb'))

In [46]:
pickled_model =pickle.load(open('Classifier.pkl','rb'))
data=[[5.4,3.9,1.7,0.4]]
pickled_model.predict(data)

array(['Iris-virginica'], dtype='<U15')