In [1]:
import pandas as pd
import numpy as np
import matplotlib as pl
import seaborn as sns

In [2]:
df= pd.read_csv("C:/Users/akash/Datasets/Social_Network_Ads.csv")
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [ ]:
df.shape

In [3]:
df.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [4]:
df.dtypes

User ID             int64
Gender             object
Age                 int64
EstimatedSalary     int64
Purchased           int64
dtype: object

In [5]:
df.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [7]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [ ]:
#logistic Regression

In [8]:
x=df.iloc[:,[2,3]]
x

Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [9]:
y=df.iloc[:,4]
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [13]:
from sklearn.preprocessing import StandardScaler
sc_x= StandardScaler()

In [15]:
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.fit_transform(x_test)

In [17]:
Classifier =LogisticRegression(random_state=0)
Classifier.fit(x_train,y_train)

LogisticRegression(random_state=0)

In [19]:
y_pred=Classifier.predict(x_test)

In [29]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[62,  4],
       [ 7, 27]], dtype=int64)

In [25]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)*100
accuracy

89.0

In [28]:
TP=cm[0,[0]]
TP

array([62], dtype=int64)

In [31]:
TN=cm[0,[1]]
TN

array([4], dtype=int64)

In [32]:
FP=cm[1,[0]]
FP

array([7], dtype=int64)

In [33]:
FN=cm[1,[1]]
FN

array([27], dtype=int64)

In [34]:
accuracy_rate=(TP+TN)/(TP+TN+FP+FN)
print(accuracy)

89.0


In [36]:
error_rate=(FP+FN)/(TP+TN+FP+FN)
print(error_rate)

[0.34]


In [37]:
precision=(TP/(TP+FP))
print(precision)

[0.89855072]


In [38]:
Recall=(TP/(TP+FN))
print(Recall)

[0.69662921]


In [40]:
specificity=(TN/TN+FP)
print(specificity)

[8.]
